version: '2'
services:
    corporatebanking-app:
        image: corporatebanking
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
                       - SPRING_DATASOURCE_URL=jdbc:postgresql://corporatebanking-postgresql:5432/corporateBanking

            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    corporatebanking-postgresql:
        extends:
            file: postgresql.yml
            service: corporatebanking-postgresql

